name: Publish to NuGet
on:
  workflow_dispatch:
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Publish to NuGet
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Config: https://github.com/brandedoutcast/publish-nuget
          PROJECT_FILE_PATH: Nekos.Net/Nekos.Net.csproj
          PACKAGE_NAME: Nekos.Net
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          TAG_FORMAT: v*
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: false
      - name: Publish to GitHub packages
        run: |
          # Config: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
          dotnet nuget add source --username Swyreee --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Swyreee/index.json"
          dotnet build Nekos.Net -c Release
          dotnet pack Nekos.Net -c Release
          dotnet nuget push "bin/Release/Nekos.Net.3.0.1.nupkg" --api-key ${{ secrets.MY_PAT }} --source "github"
